"""Regenerate CoRL 2025 browse views from raw JSON metadata.

Reads `_data/{Oral,Poster}/all_papers.json` and emits five markdown views:
  - oral.md         Oral track table (paper-number ordered)
  - poster.md       Poster track table (paper-number ordered)
  - by-field.md     Cross-track grouping by classification.field
  - by-author.md    Alphabetical index by lead-author surname
  - index.md        Conference overview with stats

`highlights.md` is NOT touched — it is hand-curated.

Usage:
    python regenerate_corl2025_views.py
"""
from __future__ import annotations

import json
from collections import defaultdict, Counter
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
CONF_DIR = SCRIPT_DIR.parent
DATA_DIR = CONF_DIR / "_data"

CONF_NAME = "CoRL 2025"
TRACKS = ("Oral", "Poster")
GENERATED_BANNER = (
    "Auto-generated by `_scripts/regenerate_corl2025_views.py`. Do not edit by hand."
)


def load_papers() -> list[dict]:
    """Load papers from `_data/{Track}/all_papers.json`, attach `track` field."""
    papers: list[dict] = []
    for track in TRACKS:
        agg = DATA_DIR / track / "all_papers.json"
        if not agg.exists():
            raise FileNotFoundError(f"missing {agg}")
        for p in json.loads(agg.read_text())["papers"]:
            p["track"] = track
            papers.append(p)
    return papers


def author_short(authors: list[str]) -> str:
    if not authors:
        return ""
    head = authors[0]
    return f"{head} et al." if len(authors) > 1 else head


def lead_surname(authors: list[str]) -> str:
    if not authors:
        return "~"
    return authors[0].split(",", 1)[0].strip()


def join_or_dash(items: list[str] | None) -> str:
    return ", ".join(items) if items else "—"


def write(target: Path, body: str) -> None:
    target.write_text(body)
    print(f"  wrote {target.relative_to(CONF_DIR)}  ({len(body):,} bytes)")


# ── Views ───────────────────────────────────────────────────────────────────

def render_track(papers: list[dict], track: str) -> str:
    rows = sorted([p for p in papers if p["track"] == track], key=lambda p: p["id"])
    lines = [
        f"# {CONF_NAME} — {track}",
        "",
        f"> {len(rows)} papers · {GENERATED_BANNER}",
        "",
        "| # | Title | Authors | Field | Model | Methods | Zotero |",
        "|---|---|---|---|---|---|---|",
    ]
    for p in rows:
        lines.append(
            f"| {p['id']} | {p['title']} | {author_short(p['authors'])} | "
            f"{join_or_dash(p.get('field'))} | {join_or_dash(p.get('models_type'))} | "
            f"{join_or_dash(p.get('methods'))} | `{p['zotero_key']}` |"
        )
    return "\n".join(lines) + "\n"


def render_by_field(papers: list[dict]) -> str:
    by_field: dict[str, list[dict]] = defaultdict(list)
    for p in papers:
        for f in p.get("field") or ["(unclassified)"]:
            by_field[f].append(p)

    lines = [
        f"# {CONF_NAME} — By Field",
        "",
        f"> {len(papers)} papers across {len(by_field)} fields · {GENERATED_BANNER}",
        "",
        "Papers can appear under multiple fields when their classification spans more than one.",
        "",
    ]
    for field in sorted(by_field, key=lambda k: (-len(by_field[k]), k)):
        rows = sorted(by_field[field], key=lambda p: (p["track"], p["id"]))
        lines += [
            f"## {field} ({len(rows)} papers)",
            "",
            "| Track | # | Title | Authors | Model | Methods | Zotero |",
            "|---|---|---|---|---|---|---|",
        ]
        for p in rows:
            lines.append(
                f"| {p['track']} | {p['id']} | {p['title']} | "
                f"{author_short(p['authors'])} | {join_or_dash(p.get('models_type'))} | "
                f"{join_or_dash(p.get('methods'))} | `{p['zotero_key']}` |"
            )
        lines.append("")
    return "\n".join(lines)


def render_by_author(papers: list[dict]) -> str:
    by_letter: dict[str, list[dict]] = defaultdict(list)
    for p in papers:
        surname = lead_surname(p["authors"])
        by_letter[surname[:1].upper() or "~"].append(p)

    lines = [
        f"# {CONF_NAME} — By Author",
        "",
        f"> Alphabetical by lead-author surname · {GENERATED_BANNER}",
        "",
    ]
    for letter in sorted(by_letter):
        rows = sorted(by_letter[letter], key=lambda p: lead_surname(p["authors"]).lower())
        lines += [f"## {letter}", ""]
        for p in rows:
            field = join_or_dash(p.get("field"))
            lines.append(
                f"- **{lead_surname(p['authors'])}** — {p['title']}  "
                f"<small>({p['track']} #{p['id']} · {field})</small>"
            )
        lines.append("")
    return "\n".join(lines)


def render_index(papers: list[dict]) -> str:
    track_counts = Counter(p["track"] for p in papers)
    field_counts: Counter = Counter()
    method_counts: Counter = Counter()
    model_counts: Counter = Counter()
    for p in papers:
        for f in p.get("field") or []: field_counts[f] += 1
        for m in p.get("methods") or []: method_counts[m] += 1
        for mt in p.get("models_type") or []: model_counts[mt] += 1

    def top_table(counter: Counter, label: str, n: int = 10) -> list[str]:
        rows = counter.most_common(n)
        out = [f"### Top {label}", "", f"| {label.title()} | Count |", "|---|---|"]
        out += [f"| {k} | {v} |" for k, v in rows]
        out.append("")
        return out

    lines = [
        f"# {CONF_NAME}",
        "",
        "Conference on Robot Learning 2025 — paper index. Source metadata under "
        "`_data/{Oral,Poster}/`; rendered views are regenerated by "
        "`_scripts/regenerate_corl2025_views.py`.",
        "",
        "## Stats",
        "",
        f"- **{track_counts['Oral']}** Oral papers",
        f"- **{track_counts['Poster']}** Poster papers",
        f"- **{sum(track_counts.values())}** total",
        "",
    ]
    lines += top_table(field_counts, "fields")
    lines += top_table(method_counts, "methods")
    lines += top_table(model_counts, "model types", n=len(model_counts))

    lines += [
        "## Browse",
        "",
        "- [Oral](oral.md) — full Oral track table",
        "- [Poster](poster.md) — full Poster track table",
        "- [By Field](by-field.md) — grouped by classification field",
        "- [By Author](by-author.md) — alphabetical by lead author",
        "- [Highlights](highlights.md) — hand-picked papers",
        "",
    ]
    return "\n".join(lines)


# ── Main ────────────────────────────────────────────────────────────────────

def main() -> None:
    print(f"[regen] loading from {DATA_DIR}")
    papers = load_papers()
    print(f"[regen] {len(papers)} papers loaded")

    write(CONF_DIR / "oral.md", render_track(papers, "Oral"))
    write(CONF_DIR / "poster.md", render_track(papers, "Poster"))
    write(CONF_DIR / "by-field.md", render_by_field(papers))
    write(CONF_DIR / "by-author.md", render_by_author(papers))
    write(CONF_DIR / "index.md", render_index(papers))
    print("[regen] done")


if __name__ == "__main__":
    main()
